In [1]:
import polars as pl 
from dbconfig import engine
print('Environment Ready!')

Environment Ready!

In [16]:
pl.Config.set_tbl_rows(100)
pl.Config.set_tbl_cols(100)
pl.Config.set_tbl_width_chars(200)
pl.Config.set_fmt_str_lengths(40000)

polars.config.Config

In [2]:
pl.read_database(
        query = """
        select table_name, column_name
        from information_schema.columns
        where table_schema = 'raw'
        order by table_name, ordinal_position
        """, connection = engine)

shape: (52, 2)
┌──────────────────────┬───────────────────────────────┐
│ table_name           ┆ column_name                   │
│ ---                  ┆ ---                           │
│ str                  ┆ str                           │
╞══════════════════════╪═══════════════════════════════╡
│ category_translation ┆ product_category_name         │
│ category_translation ┆ product_category_name_english │
│ customers            ┆ customer_id                   │
│ customers            ┆ customer_unique_id            │
│ customers            ┆ customer_zip_code_prefix      │
│ …                    ┆ …                             │
│ reviews              ┆ review_answer_timestamp       │
│ sellers              ┆ seller_id                     │
│ sellers              ┆ seller_zip_code_prefix        │
│ sellers              ┆ seller_city                   │
│ sellers              ┆ seller_state                  │
└──────────────────────┴───────────────────────────────┘

In [19]:
pl.read_database(
        query = """
        select string_agg(format(
            'select %L as table_name,
            count(*) as total_rows 
            from raw.%I', table_name, table_name),E'\nunion all\n')
        from(
            select distinct table_name
            from information_schema.columns
            where table_schema = 'raw') t;
        """,connection = engine)

shape: (1, 1)
┌─────────────────────────────────────┐
│ string_agg                          │
│ ---                                 │
│ str                                 │
╞═════════════════════════════════════╡
│ select 'order_items' as table_name, │
│             count(*) as total_rows  │
│             from raw.order_items    │
│ union all                           │
│ select 'geolocation' as table_name, │
│             count(*) as total_rows  │
│             from raw.geolocation    │
│ union all                           │
│ select 'sellers' as table_name,     │
│             count(*) as total_rows  │
│             from raw.sellers        │
│ union all                           │
│ select 'orders' as table_name,      │
│             count(*) as total_ro…   │
└─────────────────────────────────────┘

In [3]:
very_small_query = pl.read_database(
        query = """
        select string_agg( format(
            'select %L as table_name,
            %L as column_name,
            count(*) as total_rows,
            count(%s) as non_nulls,
            count(*) - count(%s) as nulls,
            round(100.00 * (count(*) - count(%s)) / count(*), 2) as null_pct
            from raw.%I', table_name, column_name, column_name, column_name, column_name, table_name), E'\nunion all\n')
        from(
            select table_name,
            column_name
            from information_schema.columns 
            where table_schema = 'raw'
            order by table_name, ordinal_position)
        """, connection = engine)

In [4]:
query = very_small_query.item()

In [5]:
null_audit = pl.read_database(
        query = query,
        connection = engine)

In [6]:
null_audit.head()

shape: (5, 6)
┌──────────────────────┬───────────────────────────────┬────────────┬───────────┬───────┬───────────────┐
│ table_name           ┆ column_name                   ┆ total_rows ┆ non_nulls ┆ nulls ┆ null_pct      │
│ ---                  ┆ ---                           ┆ ---        ┆ ---       ┆ ---   ┆ ---           │
│ str                  ┆ str                           ┆ i64        ┆ i64       ┆ i64   ┆ decimal[38,2] │
╞══════════════════════╪═══════════════════════════════╪════════════╪═══════════╪═══════╪═══════════════╡
│ category_translation ┆ product_category_name         ┆ 71         ┆ 71        ┆ 0     ┆ 0.00          │
│ category_translation ┆ product_category_name_english ┆ 71         ┆ 71        ┆ 0     ┆ 0.00          │
│ sellers              ┆ seller_state                  ┆ 3095       ┆ 3095      ┆ 0     ┆ 0.00          │
│ sellers              ┆ seller_city                   ┆ 3095       ┆ 3095      ┆ 0     ┆ 0.00          │
│ sellers              ┆ seller_zip_code_prefix        ┆ 3095       ┆ 3095      ┆ 0     ┆ 0.00          │
└──────────────────────┴───────────────────────────────┴────────────┴───────────┴───────┴───────────────┘

In [30]:
null_audit.filter(
        pl.col("nulls") > 0
        ).sort(
                "null_pct", descending = True)

shape: (13, 6)
┌────────────┬───────────────────────────────┬────────────┬───────────┬───────┬───────────────┐
│ table_name ┆ column_name                   ┆ total_rows ┆ non_nulls ┆ nulls ┆ null_pct      │
│ ---        ┆ ---                           ┆ ---        ┆ ---       ┆ ---   ┆ ---           │
│ str        ┆ str                           ┆ i64        ┆ i64       ┆ i64   ┆ decimal[38,2] │
╞════════════╪═══════════════════════════════╪════════════╪═══════════╪═══════╪═══════════════╡
│ reviews    ┆ review_comment_title          ┆ 99224      ┆ 11568     ┆ 87656 ┆ 88.34         │
│ reviews    ┆ review_comment_message        ┆ 99224      ┆ 40977     ┆ 58247 ┆ 58.70         │
│ orders     ┆ order_delivered_customer_date ┆ 99441      ┆ 96476     ┆ 2965  ┆ 2.98          │
│ products   ┆ product_photos_qty            ┆ 32951      ┆ 32341     ┆ 610   ┆ 1.85          │
│ products   ┆ product_description_lenght    ┆ 32951      ┆ 32341     ┆ 610   ┆ 1.85          │
│ products   ┆ product_name_lenght           ┆ 32951      ┆ 32341     ┆ 610   ┆ 1.85          │
│ products   ┆ product_category_name         ┆ 32951      ┆ 32341     ┆ 610   ┆ 1.85          │
│ orders     ┆ order_delivered_carrier_date  ┆ 99441      ┆ 97658     ┆ 1783  ┆ 1.79          │
│ orders     ┆ order_approved_at             ┆ 99441      ┆ 99281     ┆ 160   ┆ 0.16          │
│ products   ┆ product_width_cm              ┆ 32951      ┆ 32949     ┆ 2     ┆ 0.01          │
│ products   ┆ product_height_cm             ┆ 32951      ┆ 32949     ┆ 2     ┆ 0.01          │
│ products   ┆ product_length_cm             ┆ 32951      ┆ 32949     ┆ 2     ┆ 0.01          │
│ products   ┆ product_weight_g              ┆ 32951      ┆ 32949     ┆ 2     ┆ 0.01          │
└────────────┴───────────────────────────────┴────────────┴───────────┴───────┴───────────────┘

In [8]:
pl.read_database(
        query = """
        select count(*)
        from raw.products
        where product_category_name is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 610   │
└───────┘

In [9]:
pl.read_database(
        query = """
        select count(*)
        from raw.products
        where product_category_name is null
        and product_name_lenght is null
        and product_description_lenght is null
        and product_photos_qty is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 610   │
└───────┘

In [19]:
pl.read_database(
        query = """
        select count(distinct oi.product_id)
        from raw.order_items oi 
        join raw.products p 
        on oi.product_id = p.product_id 
        where p.product_category_name is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 610   │
└───────┘

In [20]:
pl.read_database(
        query = """
        select count(distinct seller_id)
        from raw.order_items oi 
        join raw.products p 
        on oi.product_id = p.product_id 
        where p.product_category_name is null
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 257   │
└───────┘

In [12]:
pl.read_database(
        query = """
        select order_status,
        count(*)
        from raw.orders 
        where order_delivered_customer_date is null
        group by order_status 
        order by count(*) desc;
        """, connection = engine
        )

shape: (8, 2)
┌──────────────┬───────┐
│ order_status ┆ count │
│ ---          ┆ ---   │
│ str          ┆ i64   │
╞══════════════╪═══════╡
│ shipped      ┆ 1107  │
│ canceled     ┆ 619   │
│ unavailable  ┆ 609   │
│ invoiced     ┆ 314   │
│ processing   ┆ 301   │
│ delivered    ┆ 8     │
│ created      ┆ 5     │
│ approved     ┆ 2     │
└──────────────┴───────┘

In [13]:
pl.read_database(
        query = """
        select order_status,
        count(*)
        from raw.orders 
        where order_delivered_carrier_date is null
        group by order_status 
        order by count(*) desc;
        """, connection = engine
        )

shape: (7, 2)
┌──────────────┬───────┐
│ order_status ┆ count │
│ ---          ┆ ---   │
│ str          ┆ i64   │
╞══════════════╪═══════╡
│ unavailable  ┆ 609   │
│ canceled     ┆ 550   │
│ invoiced     ┆ 314   │
│ processing   ┆ 301   │
│ created      ┆ 5     │
│ approved     ┆ 2     │
│ delivered    ┆ 2     │
└──────────────┴───────┘

In [14]:
pl.read_database(
        query = """
        select order_status,
        count(*)
        from raw.orders 
        where order_approved_at is null
        group by order_status 
        order by count(*) desc;
        """, connection = engine
        )

shape: (3, 2)
┌──────────────┬───────┐
│ order_status ┆ count │
│ ---          ┆ ---   │
│ str          ┆ i64   │
╞══════════════╪═══════╡
│ canceled     ┆ 141   │
│ delivered    ┆ 14    │
│ created      ┆ 5     │
└──────────────┴───────┘

In [15]:
pl.read_database(
        query = """
        select *
        from raw.orders 
        where order_approved_at is null
        limit 20;
        """, connection = engine
        )

shape: (20, 8)
┌───────────────────────────┬───────────────────────────┬──────────────┬──────────────────────────┬───────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┐
│ order_id                  ┆ customer_id               ┆ order_status ┆ order_purchase_timestamp ┆ order_approved_at ┆ order_delivered_carrier_ ┆ order_delivered_customer ┆ order_estimated_delivery │
│ ---                       ┆ ---                       ┆ ---          ┆ ---                      ┆ ---               ┆ date                     ┆ _date                    ┆ _date                    │
│ str                       ┆ str                       ┆ str          ┆ str                      ┆ null              ┆ ---                      ┆ ---                      ┆ ---                      │
│                           ┆                           ┆              ┆                          ┆                   ┆ str                      ┆ str                      ┆ str                      │
╞═══════════════════════════╪═══════════════════════════╪══════════════╪══════════════════════════╪═══════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╡
│ 00b1cb0320190ca0daa2c88b3 ┆ 3532ba38a3fd242259a514ac2 ┆ canceled     ┆ 2018-08-28 15:26:39      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-12 00:00:00      │
│ 5206009                   ┆ b6ae6b6                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ ed3efbd3a87bea76c2812c66a ┆ 191984a8ba4cbb2145acb4fe3 ┆ canceled     ┆ 2018-09-20 13:54:16      ┆ null              ┆ null                     ┆ null                     ┆ 2018-10-17 00:00:00      │
│ 0b32219                   ┆ 5b69664                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ df8282afe61008dc26c6c3101 ┆ aa797b187b5466bc6925aaaa4 ┆ canceled     ┆ 2017-03-04 12:14:30      ┆ null              ┆ null                     ┆ null                     ┆ 2017-04-10 00:00:00      │
│ 1474d02                   ┆ bb3bed1                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 8d4c637f1accf7a88a4555f02 ┆ b1dd715db389a2077f43174e7 ┆ canceled     ┆ 2018-08-29 16:27:49      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-13 00:00:00      │
│ 741e606                   ┆ a675d07                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 7a9d4c7f9b068337875b95465 ┆ 7f71ae48074c0cfec9195f88f ┆ canceled     ┆ 2017-05-01 16:12:39      ┆ null              ┆ null                     ┆ null                     ┆ 2017-05-30 00:00:00      │
│ 330f2fc                   ┆ cbfac55                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ ddaec6fff982b13e7e048b627 ┆ 68f4ad79cc0c2ad06e19088f5 ┆ canceled     ┆ 2016-10-04 19:41:32      ┆ null              ┆ null                     ┆ null                     ┆ 2016-11-16 00:00:00      │
│ a11d6da                   ┆ c00e9fa                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 5290c34bd38a8a095b885f139 ┆ 92af427e290117f39d9ff9085 ┆ canceled     ┆ 2018-08-21 10:25:18      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-06 00:00:00      │
│ 58db1e1                   ┆ 66072e0                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 03310aa823a66056268a3bab3 ┆ 25dbbf0c477fd4ae0880aaffb ┆ canceled     ┆ 2018-08-07 16:33:59      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-04 00:00:00      │
│ 6e827fb                   ┆ b12e8b3                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 4c8b9947280829d0a8b7e81cc ┆ 403c35c4d8813bf67b3d396b9 ┆ canceled     ┆ 2018-08-09 14:54:47      ┆ null              ┆ null                     ┆ null                     ┆ 2018-08-21 00:00:00      │
│ 249b875                   ┆ 1ca1619                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ b13ea375fe9c7288326882646 ┆ 0dc5884bc5ffba283678229f2 ┆ canceled     ┆ 2018-08-22 18:52:29      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-19 00:00:00      │
│ 38f84cf                   ┆ 7e07ff9                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ ea844c92cf978ea23321fa7fe ┆ 6ddc45ad08e6a2c885ca2255f ┆ canceled     ┆ 2018-09-13 09:56:12      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-27 00:00:00      │
│ 5871761                   ┆ c52d6df                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ e04abd8149ef81b95221e88f6 ┆ 2127dc6603ac33544953ef05e ┆ delivered    ┆ 2017-02-18 14:40:00      ┆ null              ┆ 2017-02-23 12:04:47      ┆ 2017-03-01 13:25:33      ┆ 2017-03-17 00:00:00      │
│ ed9ab6a                   ┆ c155771                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 85e05c3c9aa9834518f35d4f2 ┆ 1d07a80a15700b40cb15ff587 ┆ canceled     ┆ 2018-08-28 08:18:22      ┆ null              ┆ null                     ┆ null                     ┆ 2018-10-10 00:00:00      │
│ 86014be                   ┆ 0ee8b48                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 38a86eb53c2309d6234fc9bad ┆ 82d98198f7fb1687858e03a53 ┆ canceled     ┆ 2018-08-18 12:39:31      ┆ null              ┆ null                     ┆ null                     ┆ 2018-08-29 00:00:00      │
│ 96331ac                   ┆ 22e1621                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ c5a468ae781ffb0ec6d36ae89 ┆ ed7ef682569428c1afaf73b39 ┆ canceled     ┆ 2017-01-13 11:06:56      ┆ null              ┆ null                     ┆ null                     ┆ 2017-02-13 00:00:00      │
│ fe512b0                   ┆ a2f602b                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 2bb02fdf5637a68cd5d13c78c ┆ 8c468917b274857623298a162 ┆ canceled     ┆ 2018-08-09 10:55:10      ┆ null              ┆ null                     ┆ null                     ┆ 2018-08-17 00:00:00      │
│ 37c3376                   ┆ 7369866                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ b5359909123fa03c50bdb0cfe ┆ 438449d4af8980d107bf04571 ┆ created      ┆ 2017-12-05 01:07:52      ┆ null              ┆ null                     ┆ null                     ┆ 2018-01-11 00:00:00      │
│ d07f098                   ┆ 413a8e7                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 9380c59012c11f49c549ef8df ┆ 07838708499d3eb9da748cb10 ┆ canceled     ┆ 2018-08-15 11:05:44      ┆ null              ┆ null                     ┆ null                     ┆ 2018-09-21 00:00:00      │
│ fef1367                   ┆ b8ddf0a                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 672ab3776d5b25e5865214696 ┆ 8c8b3a28c07f67148f86f2976 ┆ canceled     ┆ 2017-05-10 11:52:51      ┆ null              ┆ null                     ┆ null                     ┆ 2017-05-26 00:00:00      │
│ 09ae774                   ┆ 04b9875                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ dba5062fbda3af4fb6c33b1e0 ┆ 964a6df3d9bdf60fe3e7b8bb6 ┆ created      ┆ 2018-02-09 17:21:04      ┆ null              ┆ null                     ┆ null                     ┆ 2018-03-07 00:00:00      │
│ 40ca38f                   ┆ 9ed893a                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
└───────────────────────────┴───────────────────────────┴──────────────┴──────────────────────────┴───────────────────┴──────────────────────────┴──────────────────────────┴──────────────────────────┘

In [21]:
pl.read_database(
        query = """
        select *
        from raw.orders 
        where order_status = 'delivered'
        and order_approved_at is null;
        """, connection = engine
        )

shape: (14, 8)
┌───────────────────────────┬───────────────────────────┬──────────────┬──────────────────────────┬───────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┐
│ order_id                  ┆ customer_id               ┆ order_status ┆ order_purchase_timestamp ┆ order_approved_at ┆ order_delivered_carrier_ ┆ order_delivered_customer ┆ order_estimated_delivery │
│ ---                       ┆ ---                       ┆ ---          ┆ ---                      ┆ ---               ┆ date                     ┆ _date                    ┆ _date                    │
│ str                       ┆ str                       ┆ str          ┆ str                      ┆ null              ┆ ---                      ┆ ---                      ┆ ---                      │
│                           ┆                           ┆              ┆                          ┆                   ┆ str                      ┆ str                      ┆ str                      │
╞═══════════════════════════╪═══════════════════════════╪══════════════╪══════════════════════════╪═══════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╡
│ e04abd8149ef81b95221e88f6 ┆ 2127dc6603ac33544953ef05e ┆ delivered    ┆ 2017-02-18 14:40:00      ┆ null              ┆ 2017-02-23 12:04:47      ┆ 2017-03-01 13:25:33      ┆ 2017-03-17 00:00:00      │
│ ed9ab6a                   ┆ c155771                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 8a9adc69528e1001fc68dd0aa ┆ 4c1ccc74e00993733742a3c78 ┆ delivered    ┆ 2017-02-18 12:45:31      ┆ null              ┆ 2017-02-23 09:01:52      ┆ 2017-03-02 10:05:06      ┆ 2017-03-21 00:00:00      │
│ ebbb54a                   ┆ 6dc3c1f                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 7013bcfc1c97fe719a7b5e05e ┆ 2941af76d38100e0f8740a374 ┆ delivered    ┆ 2017-02-18 13:29:47      ┆ null              ┆ 2017-02-22 16:25:25      ┆ 2017-03-01 08:07:38      ┆ 2017-03-17 00:00:00      │
│ 61c12db                   ┆ f1a5dc3                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 5cf925b116421afa85ee25e99 ┆ 29c35fc91fc13fb5073c8f305 ┆ delivered    ┆ 2017-02-18 16:48:35      ┆ null              ┆ 2017-02-22 11:23:10      ┆ 2017-03-09 07:28:47      ┆ 2017-03-31 00:00:00      │
│ b4c34fb                   ┆ 05d860d                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 12a95a3c06dbaec84bcfb0e2d ┆ 1e101e0daffaddce8159d25a8 ┆ delivered    ┆ 2017-02-17 13:05:55      ┆ null              ┆ 2017-02-22 11:23:11      ┆ 2017-03-02 11:09:19      ┆ 2017-03-20 00:00:00      │
│ a5d228a                   ┆ e53f2b2                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ c1d4211b3dae76144deccd6c7 ┆ 684cb238dc5b5d6366244e0e0 ┆ delivered    ┆ 2017-01-19 12:48:08      ┆ null              ┆ 2017-01-25 14:56:50      ┆ 2017-01-30 18:16:01      ┆ 2017-03-01 00:00:00      │
│ 4144a88                   ┆ 776b450                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ d69e5d356402adc8cf17e08b5 ┆ 68d081753ad4fe22fc4d410a9 ┆ delivered    ┆ 2017-02-19 01:28:47      ┆ null              ┆ 2017-02-23 03:11:48      ┆ 2017-03-02 03:41:58      ┆ 2017-03-27 00:00:00      │
│ 033acfb                   ┆ eb1ca01                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ d77031d6a3c8a52f019764e68 ┆ 0bf35cac6cc7327065da879e2 ┆ delivered    ┆ 2017-02-18 11:04:19      ┆ null              ┆ 2017-02-23 07:23:36      ┆ 2017-03-02 16:15:23      ┆ 2017-03-22 00:00:00      │
│ f211c69                   ┆ d90fae8                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 7002a78c79c519ac54022d4f8 ┆ d5de688c321096d15508faae6 ┆ delivered    ┆ 2017-01-19 22:26:59      ┆ null              ┆ 2017-01-27 11:08:05      ┆ 2017-02-06 14:22:19      ┆ 2017-03-16 00:00:00      │
│ a65e6e8                   ┆ 7a27051                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 2eecb0d85f281280f79fa00f9 ┆ a3d3c38e58b9d2dfb9207cab6 ┆ delivered    ┆ 2017-02-17 17:21:55      ┆ null              ┆ 2017-02-22 11:42:51      ┆ 2017-03-03 12:16:03      ┆ 2017-03-20 00:00:00      │
│ cec1a95                   ┆ 90b6310                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 51eb2eebd5d76a24625b31c33 ┆ 07a2a7e0f63fd8cb757ed77d4 ┆ delivered    ┆ 2017-02-18 15:52:27      ┆ null              ┆ 2017-02-23 03:09:14      ┆ 2017-03-07 13:57:47      ┆ 2017-03-29 00:00:00      │
│ dd41449                   ┆ 245623c                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 88083e8f64d95b93216418748 ┆ f67cd1a215aae2a1074638bbd ┆ delivered    ┆ 2017-02-18 22:49:19      ┆ null              ┆ 2017-02-22 11:31:06      ┆ 2017-03-02 12:06:06      ┆ 2017-03-21 00:00:00      │
│ 4d90212                   ┆ 35a223a                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 3c0b8706b065f9919d0505d3b ┆ d85919cb3c0529589c6fa617f ┆ delivered    ┆ 2017-02-17 15:53:27      ┆ null              ┆ 2017-02-22 11:31:30      ┆ 2017-03-03 11:47:47      ┆ 2017-03-23 00:00:00      │
│ 3343881                   ┆ 5f43281                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
│ 2babbb4b15e6d2dfe95e2de76 ┆ 74bebaf46603f9340e3b50c6b ┆ delivered    ┆ 2017-02-18 17:15:03      ┆ null              ┆ 2017-02-22 11:23:11      ┆ 2017-03-03 18:43:43      ┆ 2017-03-31 00:00:00      │
│ 5c97bce                   ┆ 086f992                   ┆              ┆                          ┆                   ┆                          ┆                          ┆                          │
└───────────────────────────┴───────────────────────────┴──────────────┴──────────────────────────┴───────────────────┴──────────────────────────┴──────────────────────────┴──────────────────────────┘

In [22]:
pl.read_database(
        query = """
        select date_trunc('month', order_purchase_timestamp::timestamp) as month,
        count(*)
        from raw.orders 
        where order_approved_at is null
        and order_status = 'delivered'
        group by 1
        order by 1;
        """, connection = engine
        )

shape: (2, 2)
┌─────────────────────┬───────┐
│ month               ┆ count │
│ ---                 ┆ ---   │
│ datetime[μs]        ┆ i64   │
╞═════════════════════╪═══════╡
│ 2017-01-01 00:00:00 ┆ 2     │
│ 2017-02-01 00:00:00 ┆ 12    │
└─────────────────────┴───────┘

In [2]:
pl.read_database(
        query = """
        select count(*)
        from raw.order_items oi 
        left join raw.orders o
        on oi.order_id = o.order_id
        where o.order_id is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
└───────┘

In [3]:
pl.read_database(
        query = """
        select count(*)
        from raw.order_items o 
        left join raw.products p
        on o.product_id = p.product_id
        where p.product_id is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
└───────┘

In [4]:
pl.read_database(
        query = """
        select count(*)
        from raw.order_items o 
        left join raw.sellers s 
        on o.seller_id = s.seller_id
        where s.seller_id is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
└───────┘

In [5]:
pl.read_database(
        query = """
        select count(*)
        from raw.orders o 
        left join raw.customers c 
        on o.customer_id = c.customer_id
        where c.customer_id is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
└───────┘

In [6]:
pl.read_database(
        query = """
        select count(*)
        from raw.payments p 
        left join raw.orders o 
        on p.order_id = o.order_id
        where o.order_id is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
└───────┘

In [7]:
pl.read_database(
        query = """
        select count(*)
        from raw.reviews r 
        left join raw.orders o 
        on r.order_id = o.order_id
        where o.order_id is null;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 0     │
└───────┘

In [9]:
pl.read_database(
        query = """
        select column_name
        from information_schema.columns 
        where table_schema = 'raw'
        and table_name = 'orders';
        """, connection = engine
        )

shape: (8, 1)
┌───────────────────────────────┐
│ column_name                   │
│ ---                           │
│ str                           │
╞═══════════════════════════════╡
│ order_id                      │
│ customer_id                   │
│ order_status                  │
│ order_purchase_timestamp      │
│ order_approved_at             │
│ order_delivered_carrier_date  │
│ order_delivered_customer_date │
│ order_estimated_delivery_date │
└───────────────────────────────┘

In [11]:
pl.read_database(
        query = """
        select order_id
        from raw.orders
        where order_approved_at is not null
        and order_purchase_timestamp::timestamp >
        order_approved_at::timestamp;
        """, connection = engine
        )

shape: (0, 1)
┌──────────┐
│ order_id │
│ ---      │
│ null     │
╞══════════╡
└──────────┘

In [21]:
pl.read_database(
        query = """
        select *
        from raw.orders
        where order_approved_at is not null
        and order_approved_at::timestamp >
        order_delivered_carrier_date::timestamp;
        """, connection = engine
        )

shape: (1_359, 8)
┌──────────────────────────┬──────────────────────────┬──────────────┬──────────────────────────┬─────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┐
│ order_id                 ┆ customer_id              ┆ order_status ┆ order_purchase_timestamp ┆ order_approved_at   ┆ order_delivered_carrier_ ┆ order_delivered_customer ┆ order_estimated_delivery │
│ ---                      ┆ ---                      ┆ ---          ┆ ---                      ┆ ---                 ┆ date                     ┆ _date                    ┆ _date                    │
│ str                      ┆ str                      ┆ str          ┆ str                      ┆ str                 ┆ ---                      ┆ ---                      ┆ ---                      │
│                          ┆                          ┆              ┆                          ┆                     ┆ str                      ┆ str                      ┆ str                      │
╞══════════════════════════╪══════════════════════════╪══════════════╪══════════════════════════╪═════════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╡
│ dcb36b511fcac050b97cd5c0 ┆ 3b6828a50ffe546942b7a473 ┆ delivered    ┆ 2018-06-07 19:03:12      ┆ 2018-06-12 23:31:02 ┆ 2018-06-11 14:54:00      ┆ 2018-06-21 15:34:32      ┆ 2018-07-04 00:00:00      │
│ 5de84dc3                 ┆ d70ac0fc                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 688052146432ef8253587b93 ┆ 81e08b08e5ed4472008030d7 ┆ delivered    ┆ 2018-04-22 08:48:13      ┆ 2018-04-24 18:25:22 ┆ 2018-04-23 19:19:14      ┆ 2018-04-24 19:31:58      ┆ 2018-05-15 00:00:00      │
│ 0b01a06d                 ┆ 0327c71f                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 58d4c4747ee059eeeb865b34 ┆ 1755fad7863475346bc6c377 ┆ delivered    ┆ 2018-07-21 12:49:32      ┆ 2018-07-26 23:31:53 ┆ 2018-07-24 12:57:00      ┆ 2018-07-25 23:58:19      ┆ 2018-07-31 00:00:00      │
│ 9b41f53a                 ┆ 3fe055d3                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 412fccb2b44a99b36714bca3 ┆ c6865c523687cb3f235aa599 ┆ delivered    ┆ 2018-07-22 22:30:05      ┆ 2018-07-23 12:31:53 ┆ 2018-07-23 12:24:00      ┆ 2018-07-24 19:26:42      ┆ 2018-07-31 00:00:00      │
│ fef8ad7b                 ┆ afef1710                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 56a4ac10a4a8f2ba7693523b ┆ 78438ba6ace7d2cb023dbbc8 ┆ delivered    ┆ 2018-07-22 13:04:47      ┆ 2018-07-27 23:31:09 ┆ 2018-07-24 14:03:00      ┆ 2018-07-28 00:05:39      ┆ 2018-08-06 00:00:00      │
│ b439eede                 ┆ 1b083562                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 32e4fa9bb468884309b58b93 ┆ e54367d4b00c5cb76d2dfe71 ┆ delivered    ┆ 2018-07-04 16:49:21      ┆ 2018-07-05 16:33:06 ┆ 2018-07-05 14:50:00      ┆ 2018-07-07 14:41:18      ┆ 2018-07-23 00:00:00      │
│ 48de70c3                 ┆ b9bdb89c                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 4df92d82d79c3b52c7138679 ┆ ba0660bf3fffe505ee892e15 ┆ delivered    ┆ 2018-07-24 11:32:11      ┆ 2018-07-29 23:30:52 ┆ 2018-07-26 14:46:00      ┆ 2018-07-27 18:55:57      ┆ 2018-08-06 00:00:00      │
│ fa9b07fc                 ┆ 3a2fbd49                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 16e38caa92e342c7780f6883 ┆ d29935fdaf4a76f34653da3d ┆ delivered    ┆ 2018-05-07 01:09:09      ┆ 2018-05-07 16:52:39 ┆ 2018-05-07 15:09:00      ┆ 2018-05-24 00:31:18      ┆ 2018-06-07 00:00:00      │
│ 2f832d4d                 ┆ ef4f2a24                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ b9afddbdcfadc9a87b41a832 ┆ 85c6af75161b8b2b1af98e82 ┆ delivered    ┆ 2018-08-16 13:50:48      ┆ 2018-08-16 14:05:13 ┆ 2018-08-16 13:27:00      ┆ 2018-08-24 14:58:37      ┆ 2018-09-04 00:00:00      │
│ 71c3e888                 ┆ b5a6a5a5                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6051e6d3da9a50b7325cbe9c ┆ c25122206bfcb3ffa950706e ┆ delivered    ┆ 2018-07-03 23:40:16      ┆ 2018-07-05 16:31:26 ┆ 2018-07-04 12:14:00      ┆ 2018-07-05 22:52:28      ┆ 2018-07-19 00:00:00      │
│ 81025062                 ┆ 1cb10f2b                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 7ebe19943d85e81a7b0eb108 ┆ fa3a8736d5ae8f7df9b0a415 ┆ delivered    ┆ 2018-07-22 10:28:14      ┆ 2018-07-23 11:31:43 ┆ 2018-07-23 10:09:00      ┆ 2018-07-26 16:42:42      ┆ 2018-08-15 00:00:00      │
│ 681276b7                 ┆ 4d0b14dc                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 95fa26b6ea476ed040e592e0 ┆ 9aad6db5643769b3d802a873 ┆ delivered    ┆ 2018-06-06 13:48:42      ┆ 2018-06-06 14:13:02 ┆ 2018-06-06 14:02:00      ┆ 2018-06-11 16:55:40      ┆ 2018-07-12 00:00:00      │
│ a825d6f0                 ┆ 28ec31e2                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ c6512da3ccb5263223de71b8 ┆ d6e565ef81b0c1256bf82760 ┆ delivered    ┆ 2018-07-04 11:38:50      ┆ 2018-07-05 16:40:14 ┆ 2018-07-04 14:29:00      ┆ 2018-07-06 17:18:32      ┆ 2018-07-17 00:00:00      │
│ 888d4db1                 ┆ 40252672                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ cee9f1845c95efd83885a0b2 ┆ 4d47b7a61cf3d32d4ec12b53 ┆ delivered    ┆ 2018-07-29 12:47:00      ┆ 2018-08-01 16:31:40 ┆ 2018-07-31 15:00:00      ┆ 2018-08-03 18:20:55      ┆ 2018-08-10 00:00:00      │
│ f7a22b83                 ┆ 1a57539b                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ ad133696906f6a78826daa09 ┆ e6f5b234bb0d847f10eebd70 ┆ delivered    ┆ 2018-06-15 15:41:22      ┆ 2018-06-15 16:19:23 ┆ 2018-06-15 14:52:00      ┆ 2018-06-22 18:09:37      ┆ 2018-07-18 00:00:00      │
│ 11b7daec                 ┆ 130c5d49                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 0fe8aad910ff05e73b0ddb0a ┆ 100a8d4dd80b65dc63ffb17f ┆ delivered    ┆ 2018-07-01 20:11:26      ┆ 2018-07-05 16:02:47 ┆ 2018-07-03 10:21:00      ┆ 2018-07-06 18:41:54      ┆ 2018-07-26 00:00:00      │
│ 89e61b21                 ┆ dd39ba28                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 59dba471cbd7e791c3bb0d83 ┆ c6de1ceaec9afb41c51b6182 ┆ delivered    ┆ 2018-07-04 17:15:18      ┆ 2018-07-05 16:33:22 ┆ 2018-07-05 12:46:00      ┆ 2018-07-07 12:52:32      ┆ 2018-07-17 00:00:00      │
│ aa705c49                 ┆ 11d9f118                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 74e033208dc13a7b8127eb8e ┆ 72fcbb1145f2889eddcba6d6 ┆ delivered    ┆ 2018-05-02 10:48:44      ┆ 2018-05-02 11:13:45 ┆ 2018-05-02 09:49:00      ┆ 2018-05-07 23:06:36      ┆ 2018-05-29 00:00:00      │
│ 73d09b76                 ┆ c1d6c090                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ dda3e0dbde3a2cd09432650b ┆ ed7abe2bf6dacb66b55c2beb ┆ delivered    ┆ 2018-04-22 20:13:58      ┆ 2018-04-24 18:37:08 ┆ 2018-04-24 16:22:39      ┆ 2018-05-09 19:58:31      ┆ 2018-05-16 00:00:00      │
│ 3634582d                 ┆ f0d2adaf                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ a6b58794fd2ba533359a76c0 ┆ ccd8e3459ad58ae538c9d2cf ┆ delivered    ┆ 2018-05-14 15:18:23      ┆ 2018-05-14 15:33:35 ┆ 2018-05-14 13:46:00      ┆ 2018-05-19 19:33:32      ┆ 2018-06-08 00:00:00      │
│ 8df576e3                 ┆ 35532ba4                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6672ea757b340c6ebd644244 ┆ 8070cecab3f3dbd764a54962 ┆ delivered    ┆ 2018-07-03 09:00:42      ┆ 2018-07-05 16:31:59 ┆ 2018-07-04 15:11:00      ┆ 2018-07-05 17:12:44      ┆ 2018-07-17 00:00:00      │
│ a2c982ae                 ┆ 3cfa6243                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ de6167039d6c71c0bea5a5d3 ┆ fa59e3b76be4ec3ab0fa0500 ┆ delivered    ┆ 2018-07-04 17:27:56      ┆ 2018-07-05 16:22:17 ┆ 2018-07-05 14:06:00      ┆ 2018-07-12 17:32:31      ┆ 2018-08-09 00:00:00      │
│ b9437082                 ┆ 0e7bf6c2                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ eb3b5ecbc980ff057c188ea3 ┆ 3b9470ed68cc82d8fdaaf97d ┆ delivered    ┆ 2018-07-04 14:54:19      ┆ 2018-07-05 16:09:14 ┆ 2018-07-04 16:13:00      ┆ 2018-07-09 12:32:50      ┆ 2018-07-23 00:00:00      │
│ b3eaf722                 ┆ 552e8fd2                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 07ad2a87dfce684f0b6a2388 ┆ fe196aba95e52d084e7bb60d ┆ delivered    ┆ 2017-04-27 08:26:54      ┆ 2017-04-28 11:41:28 ┆ 2017-04-28 10:05:52      ┆ 2017-05-15 10:09:22      ┆ 2017-05-29 00:00:00      │
│ 6db925c9                 ┆ bd8a23f1                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 5792e0b1c8c8a2bf53af468c ┆ 5c427f06e7fcf902e3097435 ┆ delivered    ┆ 2018-07-26 13:25:14      ┆ 2018-07-26 13:35:14 ┆ 2018-07-26 12:42:00      ┆ 2018-07-30 14:45:02      ┆ 2018-08-09 00:00:00      │
│ 9a422c88                 ┆ 16e2c580                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ f384f4edb05c390598d9010e ┆ db8d12f33acf6a08a434eda1 ┆ delivered    ┆ 2018-04-20 14:45:57      ┆ 2018-04-24 18:39:10 ┆ 2018-04-21 01:32:06      ┆ 2018-04-30 13:12:39      ┆ 2018-05-16 00:00:00      │
│ a97f7f4e                 ┆ 69d25106                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 3f6a06dd65ecc8c3c8bf73dd ┆ 88ca1a52550c2c65c9b75121 ┆ delivered    ┆ 2018-06-29 11:19:19      ┆ 2018-07-05 16:04:10 ┆ 2018-07-04 13:55:00      ┆ 2018-07-13 13:24:41      ┆ 2018-07-27 00:00:00      │
│ 9f5ade29                 ┆ cc26b060                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6d5f62b312ef08610aa99b1a ┆ 2c58296eab043d713ee5fc66 ┆ delivered    ┆ 2018-07-05 14:59:58      ┆ 2018-07-05 16:30:53 ┆ 2018-07-05 16:08:00      ┆ 2018-07-10 21:04:13      ┆ 2018-08-03 00:00:00      │
│ 365ec10b                 ┆ 9f6aba05                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 31abfb3d839221bf8dc8165f ┆ f62b26b783dc075ee45d0525 ┆ delivered    ┆ 2018-07-04 11:05:34      ┆ 2018-07-05 16:32:36 ┆ 2018-07-05 07:38:00      ┆ 2018-07-09 10:16:57      ┆ 2018-07-24 00:00:00      │
│ bd494c2f                 ┆ eb2649dc                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6e57e23ecac1ae8812866576 ┆ 2dda54e25d0984e12705c84d ┆ delivered    ┆ 2018-08-09 17:36:47      ┆ 2018-08-20 15:55:42 ┆ 2018-08-14 13:26:00      ┆ 2018-08-17 16:45:45      ┆ 2018-09-06 00:00:00      │
│ 94444267                 ┆ 4030e6e0                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ d65ef0f73f00ef3755af2d8e ┆ 754580db05fdc599ca4532c0 ┆ delivered    ┆ 2018-04-23 08:58:06      ┆ 2018-04-24 18:14:15 ┆ 2018-04-23 19:07:40      ┆ 2018-05-03 20:48:32      ┆ 2018-05-15 00:00:00      │
│ f6138ba5                 ┆ 9a328da2                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ e1489cb4d16876c628a2dadb ┆ ac618c81651b6ff8e20a1213 ┆ delivered    ┆ 2018-04-22 09:34:54      ┆ 2018-04-24 19:04:58 ┆ 2018-04-23 18:21:31      ┆ 2018-04-26 19:06:40      ┆ 2018-05-16 00:00:00      │
│ 8e675c9a                 ┆ 85f27320                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 643efaf4eddc8f0b4f71b167 ┆ d7d536ccde7b524ac5a42e24 ┆ delivered    ┆ 2018-07-02 21:45:21      ┆ 2018-07-05 16:27:02 ┆ 2018-07-04 14:55:00      ┆ 2018-07-09 19:48:46      ┆ 2018-07-25 00:00:00      │
│ 4c882fa4                 ┆ b000d982                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ e6fad28cb7f01e461467af95 ┆ c57928c036644588414e8646 ┆ delivered    ┆ 2018-04-20 17:11:26      ┆ 2018-04-24 18:45:48 ┆ 2018-04-23 17:52:52      ┆ 2018-05-06 16:46:43      ┆ 2018-05-17 00:00:00      │
│ 9930ae8a                 ┆ 83ff1da2                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 7cb67275a494651008ed5b1f ┆ 84c705277cb95c7f347ada3c ┆ delivered    ┆ 2018-06-30 12:14:21      ┆ 2018-07-05 16:27:53 ┆ 2018-07-03 10:18:00      ┆ 2018-07-11 14:52:43      ┆ 2018-08-01 00:00:00      │
│ 0353ddce                 ┆ e5f1bbd9                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ d2c902f172e80f22126d53d9 ┆ 8a320a211ebebf7ce02c6a51 ┆ delivered    ┆ 2018-07-03 20:52:04      ┆ 2018-07-05 16:33:24 ┆ 2018-07-05 13:14:00      ┆ 2018-07-06 18:12:25      ┆ 2018-07-17 00:00:00      │
│ ff7871b2                 ┆ 4f0aaeac                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 3d47aacc4c27ad170b100469 ┆ 959d795bc3b33ca52a761718 ┆ delivered    ┆ 2018-07-30 21:31:03      ┆ 2018-08-01 16:31:30 ┆ 2018-07-31 12:29:00      ┆ 2018-08-09 16:08:49      ┆ 2018-09-06 00:00:00      │
│ 5eb0c359                 ┆ ec8f9135                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6b654c2dc2e7c610cb22c325 ┆ 5239179f060acba3aae48fdc ┆ delivered    ┆ 2018-07-04 10:15:33      ┆ 2018-07-05 16:09:25 ┆ 2018-07-05 12:30:00      ┆ 2018-07-14 14:28:31      ┆ 2018-07-17 00:00:00      │
│ fb723057                 ┆ 19d479ea                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6e60346a3ee3876c1e4bc89c ┆ 2231986257f0ec3bf5abbc49 ┆ delivered    ┆ 2018-05-07 00:45:02      ┆ 2018-05-07 15:13:42 ┆ 2018-05-07 14:52:00      ┆ 2018-05-15 13:12:19      ┆ 2018-06-01 00:00:00      │
│ 597ffcb8                 ┆ d3320e9b                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ c3eb293fd154223498b6551a ┆ 1701ed88b1e8cb21051660d7 ┆ delivered    ┆ 2018-07-19 14:06:04      ┆ 2018-07-19 14:22:51 ┆ 2018-07-19 13:49:00      ┆ 2018-07-24 19:35:36      ┆ 2018-08-06 00:00:00      │
│ 728203e8                 ┆ 0d11d038                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 1594012ccc1b0770373ce691 ┆ e957d597f76d275f40a84839 ┆ delivered    ┆ 2018-04-23 19:05:57      ┆ 2018-04-24 19:17:00 ┆ 2018-04-24 12:48:39      ┆ 2018-04-27 22:08:35      ┆ 2018-05-08 00:00:00      │
│ d697e5ae                 ┆ 7fb6c7c3                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 846de1a3e7ca6bf29333e1db ┆ fed9258e995bc38766aea4fc ┆ delivered    ┆ 2018-01-30 11:51:07      ┆ 2018-02-04 23:31:38 ┆ 2018-01-31 19:48:36      ┆ 2018-02-08 21:52:09      ┆ 2018-03-02 00:00:00      │
│ 02040ab6                 ┆ dead8676                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ b777b7d618ee48ec7cf64aeb ┆ 2b83d4c1da04d92aceb19710 ┆ delivered    ┆ 2018-08-09 11:47:22      ┆ 2018-08-09 14:26:08 ┆ 2018-08-09 14:24:00      ┆ 2018-08-10 15:41:50      ┆ 2018-08-15 00:00:00      │
│ 188e9da5                 ┆ d0a59ef9                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 862cca64868df4c3a3f0058a ┆ 58f2a48696b2cf8da50fcb21 ┆ delivered    ┆ 2018-04-19 09:43:15      ┆ 2018-04-24 18:14:28 ┆ 2018-04-23 19:32:56      ┆ 2018-04-26 16:46:37      ┆ 2018-05-18 00:00:00      │
│ 93aef465                 ┆ f8512c14                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ f16dee6de72d9dcf6b644a19 ┆ 00b96a156e6827442e5ec7c6 ┆ delivered    ┆ 2018-04-21 15:10:45      ┆ 2018-04-24 19:28:02 ┆ 2018-04-23 21:08:49      ┆ 2018-04-26 21:57:31      ┆ 2018-05-16 00:00:00      │
│ 233a39da                 ┆ 20a39d24                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 0acfe927eda045512670dbbf ┆ c56ac9e8772a402f6a167237 ┆ delivered    ┆ 2018-04-21 15:10:55      ┆ 2018-04-24 18:58:50 ┆ 2018-04-23 20:34:32      ┆ 2018-04-27 13:31:48      ┆ 2018-05-17 00:00:00      │
│ 763b330a                 ┆ b0c13f28                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 03e94224875e6dec154cc7a1 ┆ bb7651b2df4512e6c29ff35a ┆ delivered    ┆ 2018-04-23 10:09:03      ┆ 2018-04-24 18:11:03 ┆ 2018-04-24 17:42:08      ┆ 2018-04-25 18:58:59      ┆ 2018-05-08 00:00:00      │

In [27]:
pl.read_database(
        query = """
        with anamolies as (
        select *
        from raw.orders
        where order_approved_at is not null
        and order_approved_at::timestamp >
        order_delivered_carrier_date::timestamp )

        select order_id,
        order_purchase_timestamp,
        order_approved_at,
        order_delivered_carrier_date,
        order_delivered_customer_date
        from anamolies;
        """, connection = engine
        )

shape: (1_359, 5)
┌──────────────────────────────────┬──────────────────────────┬─────────────────────┬──────────────────────────────┬───────────────────────────────┐
│ order_id                         ┆ order_purchase_timestamp ┆ order_approved_at   ┆ order_delivered_carrier_date ┆ order_delivered_customer_date │
│ ---                              ┆ ---                      ┆ ---                 ┆ ---                          ┆ ---                           │
│ str                              ┆ str                      ┆ str                 ┆ str                          ┆ str                           │
╞══════════════════════════════════╪══════════════════════════╪═════════════════════╪══════════════════════════════╪═══════════════════════════════╡
│ dcb36b511fcac050b97cd5c05de84dc3 ┆ 2018-06-07 19:03:12      ┆ 2018-06-12 23:31:02 ┆ 2018-06-11 14:54:00          ┆ 2018-06-21 15:34:32           │
│ 688052146432ef8253587b930b01a06d ┆ 2018-04-22 08:48:13      ┆ 2018-04-24 18:25:22 ┆ 2018-04-23 19:19:14          ┆ 2018-04-24 19:31:58           │
│ 58d4c4747ee059eeeb865b349b41f53a ┆ 2018-07-21 12:49:32      ┆ 2018-07-26 23:31:53 ┆ 2018-07-24 12:57:00          ┆ 2018-07-25 23:58:19           │
│ 412fccb2b44a99b36714bca3fef8ad7b ┆ 2018-07-22 22:30:05      ┆ 2018-07-23 12:31:53 ┆ 2018-07-23 12:24:00          ┆ 2018-07-24 19:26:42           │
│ 56a4ac10a4a8f2ba7693523bb439eede ┆ 2018-07-22 13:04:47      ┆ 2018-07-27 23:31:09 ┆ 2018-07-24 14:03:00          ┆ 2018-07-28 00:05:39           │
│ 32e4fa9bb468884309b58b9348de70c3 ┆ 2018-07-04 16:49:21      ┆ 2018-07-05 16:33:06 ┆ 2018-07-05 14:50:00          ┆ 2018-07-07 14:41:18           │
│ 4df92d82d79c3b52c7138679fa9b07fc ┆ 2018-07-24 11:32:11      ┆ 2018-07-29 23:30:52 ┆ 2018-07-26 14:46:00          ┆ 2018-07-27 18:55:57           │
│ 16e38caa92e342c7780f68832f832d4d ┆ 2018-05-07 01:09:09      ┆ 2018-05-07 16:52:39 ┆ 2018-05-07 15:09:00          ┆ 2018-05-24 00:31:18           │
│ b9afddbdcfadc9a87b41a83271c3e888 ┆ 2018-08-16 13:50:48      ┆ 2018-08-16 14:05:13 ┆ 2018-08-16 13:27:00          ┆ 2018-08-24 14:58:37           │
│ 6051e6d3da9a50b7325cbe9c81025062 ┆ 2018-07-03 23:40:16      ┆ 2018-07-05 16:31:26 ┆ 2018-07-04 12:14:00          ┆ 2018-07-05 22:52:28           │
│ 7ebe19943d85e81a7b0eb108681276b7 ┆ 2018-07-22 10:28:14      ┆ 2018-07-23 11:31:43 ┆ 2018-07-23 10:09:00          ┆ 2018-07-26 16:42:42           │
│ 95fa26b6ea476ed040e592e0a825d6f0 ┆ 2018-06-06 13:48:42      ┆ 2018-06-06 14:13:02 ┆ 2018-06-06 14:02:00          ┆ 2018-06-11 16:55:40           │
│ c6512da3ccb5263223de71b8888d4db1 ┆ 2018-07-04 11:38:50      ┆ 2018-07-05 16:40:14 ┆ 2018-07-04 14:29:00          ┆ 2018-07-06 17:18:32           │
│ cee9f1845c95efd83885a0b2f7a22b83 ┆ 2018-07-29 12:47:00      ┆ 2018-08-01 16:31:40 ┆ 2018-07-31 15:00:00          ┆ 2018-08-03 18:20:55           │
│ ad133696906f6a78826daa0911b7daec ┆ 2018-06-15 15:41:22      ┆ 2018-06-15 16:19:23 ┆ 2018-06-15 14:52:00          ┆ 2018-06-22 18:09:37           │
│ 0fe8aad910ff05e73b0ddb0a89e61b21 ┆ 2018-07-01 20:11:26      ┆ 2018-07-05 16:02:47 ┆ 2018-07-03 10:21:00          ┆ 2018-07-06 18:41:54           │
│ 59dba471cbd7e791c3bb0d83aa705c49 ┆ 2018-07-04 17:15:18      ┆ 2018-07-05 16:33:22 ┆ 2018-07-05 12:46:00          ┆ 2018-07-07 12:52:32           │
│ 74e033208dc13a7b8127eb8e73d09b76 ┆ 2018-05-02 10:48:44      ┆ 2018-05-02 11:13:45 ┆ 2018-05-02 09:49:00          ┆ 2018-05-07 23:06:36           │
│ dda3e0dbde3a2cd09432650b3634582d ┆ 2018-04-22 20:13:58      ┆ 2018-04-24 18:37:08 ┆ 2018-04-24 16:22:39          ┆ 2018-05-09 19:58:31           │
│ a6b58794fd2ba533359a76c08df576e3 ┆ 2018-05-14 15:18:23      ┆ 2018-05-14 15:33:35 ┆ 2018-05-14 13:46:00          ┆ 2018-05-19 19:33:32           │
│ 6672ea757b340c6ebd644244a2c982ae ┆ 2018-07-03 09:00:42      ┆ 2018-07-05 16:31:59 ┆ 2018-07-04 15:11:00          ┆ 2018-07-05 17:12:44           │
│ de6167039d6c71c0bea5a5d3b9437082 ┆ 2018-07-04 17:27:56      ┆ 2018-07-05 16:22:17 ┆ 2018-07-05 14:06:00          ┆ 2018-07-12 17:32:31           │
│ eb3b5ecbc980ff057c188ea3b3eaf722 ┆ 2018-07-04 14:54:19      ┆ 2018-07-05 16:09:14 ┆ 2018-07-04 16:13:00          ┆ 2018-07-09 12:32:50           │
│ 07ad2a87dfce684f0b6a23886db925c9 ┆ 2017-04-27 08:26:54      ┆ 2017-04-28 11:41:28 ┆ 2017-04-28 10:05:52          ┆ 2017-05-15 10:09:22           │
│ 5792e0b1c8c8a2bf53af468c9a422c88 ┆ 2018-07-26 13:25:14      ┆ 2018-07-26 13:35:14 ┆ 2018-07-26 12:42:00          ┆ 2018-07-30 14:45:02           │
│ f384f4edb05c390598d9010ea97f7f4e ┆ 2018-04-20 14:45:57      ┆ 2018-04-24 18:39:10 ┆ 2018-04-21 01:32:06          ┆ 2018-04-30 13:12:39           │
│ 3f6a06dd65ecc8c3c8bf73dd9f5ade29 ┆ 2018-06-29 11:19:19      ┆ 2018-07-05 16:04:10 ┆ 2018-07-04 13:55:00          ┆ 2018-07-13 13:24:41           │
│ 6d5f62b312ef08610aa99b1a365ec10b ┆ 2018-07-05 14:59:58      ┆ 2018-07-05 16:30:53 ┆ 2018-07-05 16:08:00          ┆ 2018-07-10 21:04:13           │
│ 31abfb3d839221bf8dc8165fbd494c2f ┆ 2018-07-04 11:05:34      ┆ 2018-07-05 16:32:36 ┆ 2018-07-05 07:38:00          ┆ 2018-07-09 10:16:57           │
│ 6e57e23ecac1ae881286657694444267 ┆ 2018-08-09 17:36:47      ┆ 2018-08-20 15:55:42 ┆ 2018-08-14 13:26:00          ┆ 2018-08-17 16:45:45           │
│ d65ef0f73f00ef3755af2d8ef6138ba5 ┆ 2018-04-23 08:58:06      ┆ 2018-04-24 18:14:15 ┆ 2018-04-23 19:07:40          ┆ 2018-05-03 20:48:32           │
│ e1489cb4d16876c628a2dadb8e675c9a ┆ 2018-04-22 09:34:54      ┆ 2018-04-24 19:04:58 ┆ 2018-04-23 18:21:31          ┆ 2018-04-26 19:06:40           │
│ 643efaf4eddc8f0b4f71b1674c882fa4 ┆ 2018-07-02 21:45:21      ┆ 2018-07-05 16:27:02 ┆ 2018-07-04 14:55:00          ┆ 2018-07-09 19:48:46           │
│ e6fad28cb7f01e461467af959930ae8a ┆ 2018-04-20 17:11:26      ┆ 2018-04-24 18:45:48 ┆ 2018-04-23 17:52:52          ┆ 2018-05-06 16:46:43           │
│ 7cb67275a494651008ed5b1f0353ddce ┆ 2018-06-30 12:14:21      ┆ 2018-07-05 16:27:53 ┆ 2018-07-03 10:18:00          ┆ 2018-07-11 14:52:43           │
│ d2c902f172e80f22126d53d9ff7871b2 ┆ 2018-07-03 20:52:04      ┆ 2018-07-05 16:33:24 ┆ 2018-07-05 13:14:00          ┆ 2018-07-06 18:12:25           │
│ 3d47aacc4c27ad170b1004695eb0c359 ┆ 2018-07-30 21:31:03      ┆ 2018-08-01 16:31:30 ┆ 2018-07-31 12:29:00          ┆ 2018-08-09 16:08:49           │
│ 6b654c2dc2e7c610cb22c325fb723057 ┆ 2018-07-04 10:15:33      ┆ 2018-07-05 16:09:25 ┆ 2018-07-05 12:30:00          ┆ 2018-07-14 14:28:31           │
│ 6e60346a3ee3876c1e4bc89c597ffcb8 ┆ 2018-05-07 00:45:02      ┆ 2018-05-07 15:13:42 ┆ 2018-05-07 14:52:00          ┆ 2018-05-15 13:12:19           │
│ c3eb293fd154223498b6551a728203e8 ┆ 2018-07-19 14:06:04      ┆ 2018-07-19 14:22:51 ┆ 2018-07-19 13:49:00          ┆ 2018-07-24 19:35:36           │
│ 1594012ccc1b0770373ce691d697e5ae ┆ 2018-04-23 19:05:57      ┆ 2018-04-24 19:17:00 ┆ 2018-04-24 12:48:39          ┆ 2018-04-27 22:08:35           │
│ 846de1a3e7ca6bf29333e1db02040ab6 ┆ 2018-01-30 11:51:07      ┆ 2018-02-04 23:31:38 ┆ 2018-01-31 19:48:36          ┆ 2018-02-08 21:52:09           │
│ b777b7d618ee48ec7cf64aeb188e9da5 ┆ 2018-08-09 11:47:22      ┆ 2018-08-09 14:26:08 ┆ 2018-08-09 14:24:00          ┆ 2018-08-10 15:41:50           │
│ 862cca64868df4c3a3f0058a93aef465 ┆ 2018-04-19 09:43:15      ┆ 2018-04-24 18:14:28 ┆ 2018-04-23 19:32:56          ┆ 2018-04-26 16:46:37           │
│ f16dee6de72d9dcf6b644a19233a39da ┆ 2018-04-21 15:10:45      ┆ 2018-04-24 19:28:02 ┆ 2018-04-23 21:08:49          ┆ 2018-04-26 21:57:31           │
│ 0acfe927eda045512670dbbf763b330a ┆ 2018-04-21 15:10:55      ┆ 2018-04-24 18:58:50 ┆ 2018-04-23 20:34:32          ┆ 2018-04-27 13:31:48           │
│ 03e94224875e6dec154cc7a142ce5de2 ┆ 2018-04-23 10:09:03      ┆ 2018-04-24 18:11:03 ┆ 2018-04-24 17:42:08          ┆ 2018-04-25 18:58:59           │
│ 3505a2f5fdc9c1c19d2eea9bfdac56c4 ┆ 2018-07-10 17:49:08      ┆ 2018-07-13 16:06:19 ┆ 2018-07-11 14:23:00          ┆ 2018-07-23 22:58:56           │
│ b0c2a7d04b165525254254a728c50a4e ┆ 2018-06-07 13:28:30      ┆ 2018-06-07 13:57:22 ┆ 2018-06-07 13:22:00          ┆ 2018-06-21 17:36:43           │
│ 73efca6402c1b6108195348448d76147 ┆ 2018-08-04 14:49:43      ┆ 2018-08-06 14:55:21 ┆ 2018-08-06 14:55:00          ┆ 2018-08-09 23:53:30           │
│ …                                ┆ …                        ┆ …                   ┆ …                            ┆ …                             │
│ 997d3d4e4d633291f515266c98cbda13 ┆ 2018-08-25 09:46:04      ┆ 2018-08-27 13:15:03 ┆ 2018-08-27 10:43:00          ┆ 2018-08-30 22:58:26           │
│ a61b9456778de69d35a9addadfc57ca8 ┆ 2018-07-01 15:54:18      ┆ 2018-07-05 16:17:44 ┆ 2018-07-04 15:28:00          ┆ 2018-07-11 20:06:49           │
│ 4e5eab0ade6de202ed67104e84e9636d ┆ 2018-04-20 11:18:27      ┆ 2018-04-24 18:14:37 ┆ 2018-04-24 17:32:15          ┆ 2018-04-25 18:08:31           │
│ c7a7200ede6d21b5eac67705000af954 ┆ 2018-07-05 07:50:34      ┆ 2018-07-05 16:18:00 ┆ 2018-07-05 08:02:00          ┆ 2018-07-11 19:06:57           │
│ 26c2b0e7dd3eb988721bb042f783c80e ┆ 2017-08-02 08:58:27      ┆ 2017-08-04 11:33:49 ┆ 2017-08-02 20:33:04          ┆ 2017-08-10 18:16:37           │
│ 5a8a26a982045e5cd9d257b5fdef75c9 ┆ 2017-04-25 22:17:39      ┆ 2017-04-27 13:33:28 ┆ 2017-04-26 21:33:39          ┆ 2017-05-12 12:17:48           │
│ 5930304c1503cbf5928b7e38bc52e248 ┆ 2018-05-03 14:39:55      ┆ 2018-05-03 14:55:15 ┆ 2018-05-03 14:47:00          ┆ 2018-05-10 01:52:54           │
│ b18cb761efbe70da4838435a349abd07 ┆ 2018-07-04 18:39:28      ┆ 2018-07-05 16:33:14 ┆ 2018-07-05 13:21:00          ┆ 2018-07-10 22:34:39           │
│ 6d92b8b8958a7955c3184410f45293f3 ┆ 2018-04-20 19:15:39      ┆ 2018-04-24 19:25:36 ┆ 2018-04-23 18:46:46          ┆ 2018-05-08 15:21:22           │
│ 668b09e578d6cdac0eb996a3457d49a5 ┆ 2018-07-04 22:57:46      ┆ 2018-07-05 16:23:38 ┆ 2018-07-05 12:52:00          ┆ 2018-07-11 23:34:36           │
│ 2290b45124e2773329685c8dd7458e68 ┆ 2018-07-04 13:43:30      ┆ 2018-07-05 16:09:14 ┆ 2018-07-05 09:56:00          ┆ 2018-07-10 16:08:34           │
│ 04f5536db820c4ea1450c353f92d5de5 ┆ 2018-04-22 19:19:45      ┆ 2018-04-24 17:33:43 ┆ 2018-04-23 18:03:13          ┆ 2018-04-24 18:45:00           │
│ 6a7479a3e53e4e29f03b3ae5f83a5498 ┆ 2018-04-22 19:14:39      ┆ 2018-04-24 17:30:24 ┆ 2018-04-24 17:17:44          ┆ 2018-05-02 19:12:27           │
│ 766033ca0a01f26b46dfccd2ee59cf9c ┆ 2018-07-03 19:20:59      ┆ 2018-07-05 16:23:37 ┆ 2018-07-04 15:49:00          ┆ 2018-07-10 13:43:49           │
│ b2642502bf8864ede538c80b67275178 ┆ 2018-06-30 00:46:29      ┆ 2018-07-05 16:22:31 ┆ 2018-07-05 14:30:00          ┆ 2018-07-12 17:38:22           │
│ 7c91640daf4cb53f476cd9db5eb0baf5 ┆ 2018-05-21 11:07:39      ┆ 2018-05-24 17:35:04 ┆ 2018-05-21 15:05:00          ┆ 2018-06-04 19:29:20           │
│ 0a9a43ac5fe59c6c4bee2a8f9b9fcce8 ┆ 2018-07-02 08:00:35      ┆ 2018-07-05 16:02:18 ┆ 2018-07-05 11:10:00          ┆ 2018-07-10 23:12:41           │
│ 3b40ede283844ba0fbdd110f8a56792f ┆ 2018-07-18 14:35:41      ┆ 2018-07-18 14:45:20 ┆ 2018-07-18 13:06:00          ┆ 2018-07-25 17:27:25           │
│ bf63ff8d7ca75098eaba0418489ad64d ┆ 2018-08-17 13:15:40      ┆ 2018-08-17 14:30:12 ┆ 2018-08-17 14:13:00          ┆ 2018-08-27 15:34:57           │
│ 2f7629415fce83aab452e69eda981a49 ┆ 2017-04-27 23:45:38      ┆ 2017-04-28 11:43:24 ┆ 2017-04-28 10:52:58          ┆ 2017-05-04 15:09:15           │
│ 269ad8edf5c7dd6bfbe01dc68832f6ce ┆ 2018-08-16 15:38:33      ┆ 2018-08-16 15:50:19 ┆ 2018-08-16 15:34:00          ┆ 2018-08-22 22:10:59           │
│ 46ac596698e8825788743fef0d54caca ┆ 2018-05-16 15:09:03      ┆ 2018-05-16 15:34:40 ┆ 2018-05-16 13:36:00          ┆ 2018-05-22 21:33:08           │
│ b504b1a3e9c083d7bf927d4b322922eb ┆ 2018-04-22 23:50:13      ┆ 2018-04-24 19:10:33 ┆ 2018-04-24 15:49:11          ┆ 2018-04-27 17:42:45           │
│ 0eec617eceb2ecbaec84cb904530b048 ┆ 2018-07-03 14:28:36      ┆ 2018-07-05 16:11:14 ┆ 2018-07-04 13:32:00          ┆ 2018-07-09 23:56:28           │
│ f7780ea2807db31691e83f0013294035 ┆ 2018-07-30 15:22:15      ┆ 2018-07-30 15:35:16 ┆ 2018-07-30 15:00:00          ┆ 2018-08-02 18:32:30           │
│ 594bf20a8f9e5e9cf267b3ee3260679b ┆ 2017-05-04 15:27:47      ┆ 2017-05-09 22:32:38 ┆ 2017-05-08 15:27:31          ┆ 2017-05-21 13:32:37           │
│ 5a41aefdf8010bbd69a5264f69213b73 ┆ 2018-07-02 16:13:00      ┆ 2018-07-05 16:17:20 ┆ 2018-07-03 12:40:00          ┆ 2018-07-05 12:48:37           │
│ c54a7eec3c60268882826057b1f7f31b ┆ 2018-07-03 20:26:13      ┆ 2018-07-05 16:19:56 ┆ 2018-07-05 14:09:00          ┆ 2018-07-09 20:56:40           │
│ d7646ffe8fdd9e7d9557f9f7cbf04530 ┆ 2018-05-04 14:50:37      ┆ 2018-05-04 15:10:22 ┆ 2018-05-04 14:48:00          ┆ 2018-05-08 19:06:42           │
│ 7d4bbd720f893f2ce3f6e19f95c4249a ┆ 2018-05-24 11:30:54      ┆ 2018-05-25 11:37:01 ┆ 2018-05-25 11:15:00          ┆ 2018-05-29 15:17:35           │
│ 23b6026f4aa837ed95e0941208f31434 ┆ 2018-07-02 16:53:10      ┆ 2018-07-05 16:17:36 ┆ 2018-07-04 13:44:00          ┆ 2018-07-07 16:31:31           │
│ 89ca163ca854eaee18b4ba6110f524fe ┆ 2018-07-04 21:45:50      ┆ 2018-07-05 16:17:49 ┆ 2018-07-05 14:38:00          ┆ 2018-07-11 21:03:42           │
│ ed12c1acf2aa565658a1353aa0443768 ┆ 2018-04-22 16:03:31      ┆ 2018-04-24 18:59:40 ┆ 2018-04-23 19:18:50          ┆ 2018-05-18 14:32:45           │
│ 773632f583feeda7d9b063496b6526a2 ┆ 2018-07-02 16:39:17      ┆ 2018-07-05 16:27:42 ┆ 2018-07-03 12:59:00          ┆ 2018-07-13 21:18:47           │
│ 5ded8a3706eabd813685534724f066de ┆ 2018-07-18 08:46:52      ┆ 2018-07-18 09:01:48 ┆ 2018-07-18 08:44:00          ┆ 2018-07-25 13:53:17           │
│ 1378f9601350615613cc8832d6789c5d ┆ 2017-09-01 20:28:02      ┆ 2017-09-13 22:03:51 ┆ 2017-09-04 18:07:55          ┆ 2017-09-13 22:24:46           │
│ b811c8ca07716586e80c0bc4f2a6e39f ┆ 2018-04-20 18:29:15      ┆ 2018-04-24 18:49:01 ┆ 2018-04-23 18:28:42          ┆ 2018-05-01 00:32:42           │
│ d10046876c7d9f01613da59ffa6cb07f ┆ 2018-07-18 16:14:16      ┆ 2018-07-18 16:25:17 ┆ 2018-07-18 15:34:00          ┆ 2018-07-23 20:46:44           │
│ 1ab38815794efa43d269d62b98dae815 ┆ 2018-07-01 10:23:10      ┆ 2018-07-05 16:17:52 ┆ 2018-07-04 14:34:00          ┆ 2018-07-09 15:06:57           │
│ 810b8bba6a2fb6419db87fe22a4299fe ┆ 2018-05-10 11:54:32      ┆ 2018-05-10 12:56:20 ┆ 2018-05-10 12:18:00          ┆ 2018-05-15 19:54:56           │
│ 67884ec2877808808c25211dce58689b ┆ 2017-05-07 12:31:08      ┆ 2017-05-12 21:33:56 ┆ 2017-05-10 11:43:58          ┆ 2017-05-16 07:57:33           │
│ bfd9e46406df093343381a91996cb660 ┆ 2018-05-06 09:38:19      ┆ 2018-05-07 16:12:36 ┆ 2018-05-07 15:03:00          ┆ 2018-05-22 23:17:57           │
│ bf0e0772c9e81651f6f0f255ed74bf88 ┆ 2018-05-29 13:46:56      ┆ 2018-05-29 14:11:32 ┆ 2018-05-29 14:09:00          ┆ 2018-06-12 12:56:44           │
│ fba0d18dccd0e4e88943d84a0f5aa448 ┆ 2018-04-22 20:23:31      ┆ 2018-04-24 18:33:58 ┆ 2018-04-23 23:12:12          ┆ 2018-04-24 23:22:08           │
│ bb8871a92af73ddadeac0531a0787131 ┆ 2018-07-31 09:16:57      ┆ 2018-08-01 16:31:37 ┆ 2018-08-01 15:03:00          ┆ 2018-08-08 01:03:27           │
│ 240ead1a7284667e0ec71d01f80e4d5e ┆ 2018-07-02 16:30:02      ┆ 2018-07-05 16:17:59 ┆ 2018-07-05 14:11:00          ┆ 2018-07-10 23:21:47           │
│ 78008d03bd8ef7fcf1568728b316553c ┆ 2018-07-03 13:11:13      ┆ 2018-07-05 16:32:52 ┆ 2018-07-03 12:57:00          ┆ 2018-07-10 17:47:39           │
│ 76a948cd55bf22799753720d4545dd2d ┆ 2018-01-30 02:41:30      ┆ 2018-02-04 23:31:46 ┆ 2018-01-31 18:11:58          ┆ 2018-03-18 20:08:50           │
│ a6bd1f93b7ff72cc348ca07f38ec4bee ┆ 2018-04-20 17:28:40      ┆ 2018-04-24 19:26:10 ┆ 2018-04-23 17:18:40          ┆ 2018-04-28 17:38:42           │
│ 7fd85cb0143de098a4c5ab5a57bfbd91 ┆ 2017-05-04 21:05:28      ┆ 2017-05-09 22:33:28 ┆ 2017-05-09 17:02:58          ┆ 2017-05-18 06:34:38           │
└──────────────────────────────────┴──────────────────────────┴─────────────────────┴──────────────────────────────┴───────────────────────────────┘

In [18]:
pl.read_database(
        query = """
        select order_id
        from raw.orders
        where order_approved_at is not null
        and order_delivered_carrier_date::timestamp >
        order_delivered_customer_date::timestamp;
        """, connection = engine
        )

shape: (23, 1)
┌──────────────────────────────────┐
│ order_id                         │
│ ---                              │
│ str                              │
╞══════════════════════════════════╡
│ a1abeb653a4d4cd1e142ccb8c82cd069 │
│ 383aa8b2724fe452d9ccd9934a8c628b │
│ cb1134f9010d242e9515ad1c78ec0c39 │
│ dceb62e8fa94b46006c9554fed743df0 │
│ 5f9d46795c3126674e52becb3a1a517f │
│ 8c78d01de3a9009e23d6877a7cc9be20 │
│ b27af682321527a6349f1761eb3f360c │
│ 1cc3ae63caffff2d6c3ee3e78e074acf │
│ e37f11cae9985ca58f0b56f268720537 │
│ fa3e37584f4fdb1ded0e0de700dfcb4e │
│ c1e2bf2b7dd3309f2f5356c6b63968fa │
│ b866af202be0692766081310cd4085e1 │
│ 29941903985f944b0ffc49c479c1547d │
│ 76458889992169d3135b264dc13aec67 │
│ 0922ee1619de7b995648e5a8407afb91 │
│ fbffbaaa30f4077e87ec6acdb835b278 │
│ 3ee6694bb99d5a6db0deceffcd099597 │
│ 19feb5627c41ea1b36a8e50a469b3644 │
│ d5558a097766363b8e76b38c43332e8a │
│ 771c4f1f521f462e4b95619e648aaeab │
│ ea1dcb4757a844d2642547797bd5feb0 │
│ 99ad48402644a3968f2481defdc57947 │
│ f688669f48063536e082bb32d634cd46 │
└──────────────────────────────────┘

In [20]:
pl.read_database(
        query = """
        select order_id
        from raw.orders
        where order_approved_at is not null
        and order_delivered_customer_date is not null
        and order_approved_at::timestamp >
        order_delivered_customer_date::timestamp;
        """, connection = engine
        )

shape: (61, 1)
┌──────────────────────────────────┐
│ order_id                         │
│ ---                              │
│ str                              │
╞══════════════════════════════════╡
│ 58d4c4747ee059eeeb865b349b41f53a │
│ 4df92d82d79c3b52c7138679fa9b07fc │
│ 6e57e23ecac1ae881286657694444267 │
│ f222c56f035b47dfa1e069a88235d730 │
│ cf72398d0690f841271b695bbfda82d2 │
│ 6df6c9c9af6ef75b4f06f8a7b9f47e9c │
│ 1fab4ac9d85079b3da72a11475ae1685 │
│ fa962e76e50f3469ae2abfa54e6d5be0 │
│ 0467205a89711e4ec8e70ef2277e3287 │
│ ecd1661658d34312cf9ac2bf34ba3b6b │
│ 8b83251dbc9bd02530320cceb82cc03e │
│ 6d1832bd42dccbd91d1ce32da7f54492 │
│ a727355acb88d9b3e6e41fb2e3888a0e │
│ 6b80bb20190715d71c43efff617bd659 │
│ c3b8c17ee15e0e798c2e178b7d4c7f42 │
│ 5f827831438fdab57e6b6b98328b360e │
│ 0e1501cd30758f584d1fa67cc6f9493a │
│ 547b3596c03dfad1b87305e9c5a554c2 │
│ bc4854efd86d9f42140c951c595d20c1 │
│ cb0909932c118481a0e44396d80ab2e8 │
│ f5234dc943e266dc8922b4870dc9d491 │
│ 641879e47a518bfcd257cdedda69f029 │
│ 70e534acd4ff3f46956f7b4b36418474 │
│ 4e16f71b2a5ddc0266f9ddfdfd0bcfba │
│ 66e1b657a71397245290f39ffe24031e │
│ 8554cb37f7158cb0b082a841d24a4589 │
│ 5e981569f5835c96e4b288363b3b8f63 │
│ 0184d4ddb259e1a4cfc2871888cf97b8 │
│ 9a6327d5a077984fa3e3c659a24e7915 │
│ ced9d48cd170ccf0a762bf379b4723fc │
│ 5b9e437b9b8c217c1e35158aeafc2102 │
│ e73fe43cdcd166f7f0c6e3c2bf11a917 │
│ 82ffe097d8ddbf319a523b9bbe7725d5 │
│ 394d17c2b71a726e205caaeee3d2aa3d │
│ 6dcf0aeb8b1eb4021c26e1d0e9394979 │
│ 3a41d0e227b4c6fff055561af5eaca13 │
│ 59c51bdf0c3270d962625e5ebbe22fb1 │
│ be7d02ed4f9ec9a43ac0f6adade17ade │
│ 4d5e865e4b64c8b33f8a81fd14731344 │
│ f6f0b2497c5a4ca89670186757ab2684 │
│ 1809078b655469f11b429102fb296998 │
│ 70f357cca87c1162357bf3c0a993cbe5 │
│ 97823d6731e59cd6b4f9d3ea113a976e │
│ d6e3732aea036f7d71b44db75163e2f4 │
│ d15a4c4d1426b7275d538063d8fe4c6a │
│ 6d1f16f4ed292206fbeedf3b44e0ceb3 │
│ a49dc0169f9bb6d3ac9829bdebd12299 │
│ b038f6ae89bdd1fddd3b51ace3ff8b30 │
│ 6fa0c125ee7d870f6602c97e33d87bc5 │
│ 40de47dfa620d667117e4a6067b6e1ec │
│ d836abb4444d8594455e9766104e958c │
│ 746e0019b6fc6170534f81e45e8d55ec │
│ 112b993827414a482ef6534e251fad3a │
│ bc1b85147b5edbb7cbefcf5c1bd5ded9 │
│ fab28f3d1cfbe171566884703d82682e │
│ dd46ac8cf8a385a883f38119228c584e │
│ fcbf4f4ef049367f9f85af94ed3b6010 │
│ 4387477eec4b3c89b39f3f454940d059 │
│ 4f3a6e28d764cf896b1fceb0028422c8 │
│ 9c3186381b733d4304e2e416afc6bbc1 │
│ 5a41aefdf8010bbd69a5264f69213b73 │
└──────────────────────────────────┘

In [29]:
pl.read_database(
        query = """
        select count(*)
        from (
            select review_id
            from raw.reviews
            group by review_id 
            having count(*) > 1
            ) t;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 789   │
└───────┘

In [31]:
pl.read_database(
        query = """
        select count(*)
        from (
            select order_id
            from raw.reviews
            group by order_id 
            having count(*) > 1
            ) t;
        """, connection = engine
        )

shape: (1, 1)
┌───────┐
│ count │
│ ---   │
│ i64   │
╞═══════╡
│ 547   │
└───────┘

In [32]:
pl.read_database(
        query = """
        select review_id
        from raw.reviews
        group by review_id
        having count(*) > 1;
        """, connection = engine
        )

shape: (789, 1)
┌──────────────────────────────────┐
│ review_id                        │
│ ---                              │
│ str                              │
╞══════════════════════════════════╡
│ 4fea089659b78b233489192ca88d8448 │
│ e9cf1b5368603de7222e94123cc1ceb5 │
│ f9306ef54d4adecf8cca0377b9b0f957 │
│ 22a299893c5cee48be41d8fab8804e6e │
│ da8e936bc2f1b52ec626f8aa41f3df44 │
│ d8949cc65047d1fb816ac8c2500ad4b1 │
│ 393907d8e4b794865eff74489af712aa │
│ 37680aaaa05c4feca6dc54850acc4bda │
│ 3d635999da844a3b3e463959a0aff863 │
│ eb8d43b4f99e45d3c7a08abd8ef1ff41 │
│ 08528f70f579f0c830189efc523d2182 │
│ 471a7d853b152d77aefd43bc39f03d64 │
│ 58f1655df206a9a40482b929b81ee671 │
│ b85476ba79cb6e9994f1d86a60d645f8 │
│ 08a86da22498172adb6cefaa99fdfaf7 │
│ ea88898e75d153da5b7656e8e0d48fb8 │
│ b6a4180ee3b8988ed0e5048c261837a2 │
│ c9a406d3076559e35f713ec82223d39c │
│ d01f8861801088198e20d318cb4e370e │
│ 6c3c56231c45f130228a386e4d9b124a │
│ 9a07cb8136a1792e7984d827e2336d60 │
│ b50b479cf97c8998967015fac6825c58 │
│ e7452eb647855255b2045780c7e90097 │
│ d7396fb0a95a02954cbbd5c26fb02694 │
│ c557f1f8cc26c5d4acc80a7d850c1305 │
│ 35f99f8617e335ae7b1abb02b68ceb64 │
│ 29aeeca2ed21aedc552cc21421eeb983 │
│ 3295dbb1b074d724e79ef4c08482b92c │
│ 135df63f4871bf893d89ca67df0f921c │
│ 5b5d6671a9a749006c26373a40707158 │
│ 6689aabfeb781e9fc59aceb91b5de579 │
│ 5395e388be6105b6a76ddcce4557356f │
│ a6f0d222db54744afc8e7cc7c9c2bbc5 │
│ b3660036bce046fa596b3e7e45d2fa7b │
│ aaa5fba9e8840f7ea9a68f4e2c6efa0e │
│ a7bff3d04efb15f2623d790a97678437 │
│ 81b1b9877ab57bf13e0d8ffc2f550c1a │
│ a3081a4676a5126d8fc0bcbff9149708 │
│ 4b17beb9e003b44fdd0a773763cdaec4 │
│ 771654d19b26b9108952856b225ad105 │
│ 3242cc306a9218d0377831e175d62fbf │
│ 17939259ccc419f355fb4a148151fb00 │
│ 0655af56f10bc3ef8e3810610828f294 │
│ 32bfc824c23129068e5261d3e850b0dd │
│ c90c495e88650f64aca79bbb2daac46c │
│ c76d214753231e86d69154aca0bdfdda │
│ 09534ea272eea99209ff37c5c348ceb1 │
│ 6e9bca18453897350cc1ad6c1bed49ef │
│ bebd0c23d7791cb07b4eb3e459e5920b │
│ e6acae33a98861be63cf635525330891 │
│ …                                │
│ 268d71995d6c0c472faf0f13b442a00e │
│ a334abcb91df2132f817e0ae76ee5d55 │
│ b57d0eba62250faf6bbb49afc360bdb0 │
│ 3e01d982e5d8012af3a30bcb7b66645d │
│ 9a8884861c6d83bcab8cb26237a83c12 │
│ 7c7d0a7bb5f4b7e668c4e00a931ccbf4 │
│ 9bd0077d08645b60245d5f6b8896bbd7 │
│ e06bce36254ded26a11fe556ef6e61ed │
│ a935b3d67f406bac4853776d80a05220 │
│ d672a3187b060908887a8ae9808cc02a │
│ dd58af2639fcadea69893ec0ff94bdd1 │
│ d8e8c42271c8fb67b9dad95d98c8ff80 │
│ 5ad27122555c26796d02523ee8274f51 │
│ 1d5b8cc3cac5888ebfc80a0dcd337f07 │
│ c56a88a404315a0d9e412c1472dda2c4 │
│ 90514cec532749be9a0a0f16d21e4ab5 │
│ f3e832f728482bddb2d328f95e386d45 │
│ 3c37ba02da70e7b97b472dabbb75ea3e │
│ 176a37898b45f9db0b8de7641973bf53 │
│ b5c66480c76e304e904cf9c16a883113 │
│ 6902c7530ba05c8f2927697108f42732 │
│ 36ec7beab972a0bd81e25c048195342f │
│ 28ca1ef3654a32df2ec947b123a1385f │
│ 3c13b1bfbeb1111f4842bdc89f3e54f1 │
│ ed572527a5e73f537301486af48a9fe4 │
│ ae9ac61bd78536846abaf469731237d6 │
│ 0174caf0ee5964646040cd94e15ac95e │
│ bcab607c602aa2ebf22f6889eb896823 │
│ bee3c76b6017ec9deaeef78bd5dbef21 │
│ 1442a23fe4555fda0f7c7eb7ba5ae3b1 │
│ 87159a093663b2a1bb847dbb84879c41 │
│ 0546d398a833d4c33dec480bedeecfbd │
│ 68f285829ce3d732e6f8b97c60f306cb │
│ 8236417ad9cf970573cf2dfdacec47ce │
│ 7c5259bcd85c4114cd5eddef2b4089aa │
│ dce802e80645c005b51222c9948d9d89 │
│ 348f6373b7a445885d64a4d8dc9d5c21 │
│ 9ee332340e369798b47cf243f1e3f99f │
│ ad134dca6a26a91326f970a15e4c9cba │
│ 3a3c8a7cefc90bf9b10ac53451f4549e │
│ dd43a798c9e8baf7b69297bb076c517d │
│ 12476f0c366e9de86c46fbced6372d92 │
│ b54d02f7f1520b3995f84b77ab0dacb3 │
│ 70be3f25177bd0d08ab572e9c6a2281a │
│ a0689adf80eece4d3db0378bdc14949b │
│ 9a0bb4f51bdc2568e43a1e47457bd8a4 │
│ 37143879ed397a8fcb2ed49b3ffa1e44 │
│ e8f500e8052dd5fac20fee5a8c880367 │
│ edafdd48374104b52e9a45f1c290fa2a │
│ 9979f9019b0fb7755be14008181a96be │
└──────────────────────────────────┘

In [34]:
pl.read_database(
        query = """
        select * 
        from raw.reviews
        where review_id = '4fea089659b78b233489192ca88d8448';
        """, connection = engine
        )

shape: (2, 7)
┌──────────────────────────────────┬──────────────────────────────────┬──────────────┬──────────────────────┬────────────────────────┬──────────────────────┬─────────────────────────┐
│ review_id                        ┆ order_id                         ┆ review_score ┆ review_comment_title ┆ review_comment_message ┆ review_creation_date ┆ review_answer_timestamp │
│ ---                              ┆ ---                              ┆ ---          ┆ ---                  ┆ ---                    ┆ ---                  ┆ ---                     │
│ str                              ┆ str                              ┆ i64          ┆ null                 ┆ null                   ┆ str                  ┆ str                     │
╞══════════════════════════════════╪══════════════════════════════════╪══════════════╪══════════════════════╪════════════════════════╪══════════════════════╪═════════════════════════╡
│ 4fea089659b78b233489192ca88d8448 ┆ 3200257acc9dd36d1fa819e72fca7e59 ┆ 4            ┆ null                 ┆ null                   ┆ 2017-12-05 00:00:00  ┆ 2017-12-08 00:30:08     │
│ 4fea089659b78b233489192ca88d8448 ┆ 6390d8596b48fe36ecbd508af3770dec ┆ 4            ┆ null                 ┆ null                   ┆ 2017-12-05 00:00:00  ┆ 2017-12-08 00:30:08     │
└──────────────────────────────────┴──────────────────────────────────┴──────────────┴──────────────────────┴────────────────────────┴──────────────────────┴─────────────────────────┘

In [35]:
pl.read_database(
        query = """
        select *
        from raw.orders
        where order_id in (
            '3200257acc9dd36d1fa819e72fca7e59',
            '6390d8596b48fe36ecbd508af3770dec');
        """, connection = engine
        )

shape: (2, 8)
┌──────────────────────────┬──────────────────────────┬──────────────┬──────────────────────────┬─────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┐
│ order_id                 ┆ customer_id              ┆ order_status ┆ order_purchase_timestamp ┆ order_approved_at   ┆ order_delivered_carrier_ ┆ order_delivered_customer ┆ order_estimated_delivery │
│ ---                      ┆ ---                      ┆ ---          ┆ ---                      ┆ ---                 ┆ date                     ┆ _date                    ┆ _date                    │
│ str                      ┆ str                      ┆ str          ┆ str                      ┆ str                 ┆ ---                      ┆ ---                      ┆ ---                      │
│                          ┆                          ┆              ┆                          ┆                     ┆ str                      ┆ str                      ┆ str                      │
╞══════════════════════════╪══════════════════════════╪══════════════╪══════════════════════════╪═════════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╡
│ 3200257acc9dd36d1fa819e7 ┆ c8a84c4b2aea91e2cfd48a87 ┆ delivered    ┆ 2017-11-24 12:58:53      ┆ 2017-11-24 15:13:44 ┆ 2017-11-28 15:29:05      ┆ 2017-12-04 20:33:01      ┆ 2017-12-27 00:00:00      │
│ 2fca7e59                 ┆ ae2a8947                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
│ 6390d8596b48fe36ecbd508a ┆ 5f302af18bb0da175bc7b0ef ┆ delivered    ┆ 2017-11-24 12:58:54      ┆ 2017-11-24 15:13:32 ┆ 2017-11-27 21:48:39      ┆ 2017-12-05 00:32:49      ┆ 2017-12-28 00:00:00      │
│ f3770dec                 ┆ f5307451                 ┆              ┆                          ┆                     ┆                          ┆                          ┆                          │
└──────────────────────────┴──────────────────────────┴──────────────┴──────────────────────────┴─────────────────────┴──────────────────────────┴──────────────────────────┴──────────────────────────┘

In [36]:
pl.read_database(
        query = """
        select *
        from raw.order_items
        where order_id in (
            '3200257acc9dd36d1fa819e72fca7e59',
            '6390d8596b48fe36ecbd508af3770dec');
        """, connection = engine
        )

shape: (3, 7)
┌──────────────────────────────────┬───────────────┬──────────────────────────────────┬──────────────────────────────────┬─────────────────────┬────────┬───────────────┐
│ order_id                         ┆ order_item_id ┆ product_id                       ┆ seller_id                        ┆ shipping_limit_date ┆ price  ┆ freight_value │
│ ---                              ┆ ---           ┆ ---                              ┆ ---                              ┆ ---                 ┆ ---    ┆ ---           │
│ str                              ┆ i64           ┆ str                              ┆ str                              ┆ str                 ┆ f64    ┆ f64           │
╞══════════════════════════════════╪═══════════════╪══════════════════════════════════╪══════════════════════════════════╪═════════════════════╪════════╪═══════════════╡
│ 3200257acc9dd36d1fa819e72fca7e59 ┆ 1             ┆ 167b4b8c4bd0c401bea62f5e050d70a4 ┆ 25c5c91f63607446a97b143d2d535d31 ┆ 2017-12-11 15:13:44 ┆ 149.87 ┆ 16.81         │
│ 3200257acc9dd36d1fa819e72fca7e59 ┆ 2             ┆ 167b4b8c4bd0c401bea62f5e050d70a4 ┆ 25c5c91f63607446a97b143d2d535d31 ┆ 2017-12-11 15:13:44 ┆ 149.87 ┆ 16.81         │
│ 6390d8596b48fe36ecbd508af3770dec ┆ 1             ┆ e46d3c8d60e3f8b382b6f239e5af08ac ┆ 1c68394e931a64f90ea236c5ea590300 ┆ 2017-12-07 15:13:32 ┆ 679.12 ┆ 16.88         │
└──────────────────────────────────┴───────────────┴──────────────────────────────────┴──────────────────────────────────┴─────────────────────┴────────┴───────────────┘

In [37]:
pl.read_database(
        query = """
        select order_id
        from raw.reviews
        group by order_id
        having count(*) > 1;
        """, connection = engine
        )

shape: (547, 1)
┌──────────────────────────────────┐
│ order_id                         │
│ ---                              │
│ str                              │
╞══════════════════════════════════╡
│ 565b0bdb5bfef65df5a23890967586f6 │
│ 6318d8c5f6857de384c0b3186d036457 │
│ b9a528ec4ad891d009b3dc50588218f1 │
│ 6b2f7dba402cf63ca207bbe2cc05ef67 │
│ fa350da9efbba83c2957b629bf6c2c7c │
│ 61b2314bd576f3d792e46e1d56e51ee6 │
│ 95e7f49dc56e12097c265c45527a3941 │
│ a89773db642a632c5cf8534ce1a49b28 │
│ 95287dc5df93f25b90309d5acddbe02e │
│ 8e350e1e4254bd7c68913b98bde7d3a7 │
│ 5f92ad7a8f00f12846cf6f654966adc4 │
│ 9735a2f9279006018ed254377240bf4c │
│ b798fc527c548bfa5f069b5b29195275 │
│ ff850ba359507b996e8b2fbb26df8d03 │
│ 8ff88873f03f1912c00741f8e5ae6c79 │
│ 169ab175fb915582d84c0c5c95bb0fe3 │
│ 1041d437bb0a4bcfeb3a107426f2d5f5 │
│ dd73d93a25e576d8dae52c7c66b3becf │
│ b7293e3014a7261f0d26d28a1e927864 │
│ 823384842bb58973b0c88e31c6f94da9 │
│ 241ed1aad96c4cc788ee6f8ab96242ef │
│ d43872a5beeeefe86421f622da91fb38 │
│ 361e0cf744333677864a5e28558a53bc │
│ 559d606ac642899e44550f194fec7e08 │
│ 684497197738631cbe11c77e531a3220 │
│ 42ae1967f68c90bb325783ac55d761ce │
│ 4ec16f88e884232366f73009df2bf045 │
│ ec7c6bfed4adf361322a0b6d6e5bfc51 │
│ 7a502e545ea55a7ff2a035abd83c6d84 │
│ b37a7e90838d63c38152d2f8c432a726 │
│ 5123fb3580d7dd11bfd9c25321e43ed5 │
│ c1deab56eafcb4bec7703bbe7bd25137 │
│ 6540a36b3dd6a4a0922d5f57d493d9d6 │
│ 468edfd1aeeeef023e6bba4943f2cdfb │
│ 013056cfe49763c6f66bda03396c5ee3 │
│ 3ca618a967a369a20ac5f2c4e00e151a │
│ aef2bc3845eb581cecce74b769d46c6a │
│ 25cb912c6742e486c6988aaf2c8f221b │
│ 28a32ec11abbac5c27adfa4d8cbc351a │
│ e1bc1083cd7acd30d0576335373b907d │
│ b6f999c6eccbf4df9af77d67c77a8e52 │
│ 3c1098cb17277b62cfc709c7a9b500f5 │
│ 1549221b1b6e8fec6d2f9890932333f1 │
│ 250587cf0cafce7892b56a47a1697833 │
│ bb3b63f8a09bf476fd524c44fb767a31 │
│ 98c977c116f7779360e9fecffd3860b6 │
│ d07ea9203ae0a6ea15a2eacc87b4c0f7 │
│ 2792c4f95b24c1a72641cd404561bdd8 │
│ 3b132068223649635448d659e7826d12 │
│ 75df014e897510b97edbb6261ef40f82 │
│ …                                │
│ 329aacec1c0231ed21bb1e2f8f4dc1e0 │
│ f20ad794a21ea34c982e74ec18f7aaec │
│ 7433b1786e1af2042c2c4c76d3e4b750 │
│ 6f118f6a730ce35b230974f295f743f9 │
│ b45d11b61c2a68756bbbd7665d67e812 │
│ 03eba6d9fef8f5b3e811d4b5a7cca9cd │
│ 230429e6f253f9cd6561aad72ce7ee2f │
│ 095e9e0811476409362d72fa70d73a6c │
│ 246b14cc444e8a7df0afd80495dfa052 │
│ f3ee55bf50ef2f2318599425ef80107d │
│ 4464462d945bc41b8b7cc74d04722969 │
│ 6596197a74edd396e3d34c53eff4ad6f │
│ c333fbd06019caef9160f4b7ab8547d1 │
│ ace3b21c5c57456d2e2215452829073b │
│ 7845a2492ab1b4f2cf3d56c7b8da1446 │
│ ab71e5dff0ed652f1559e1860391bd22 │
│ fc3d87913825143fa41c48e40267c47a │
│ 5f4415c3829ad05566ee455a5344d07d │
│ 5f7252bf13701d879f6fc28e72b71a9b │
│ 6b99ff92735c747557e84a5f5cd7a560 │
│ 2f8f31eb2f7b6572836d662a6625c8e4 │
│ 4fafa25ee16300a26f7ef92f3d15b58b │
│ 44b7f7a59d7d3d4c6d72380e3af10e80 │
│ ccb44718a5b5b8bde31b24e888d56d09 │
│ 5c2049caca936695cfa43805ebe7d8e3 │
│ c0db7d31ace61fc360a3eaa34dd3457c │
│ e68635b5cb368d061f2acf5de4d617e7 │
│ 1bc1acc1a9efde3aaa00688fc9d33d2a │
│ bcb0343717a9e0265e156e34c25c3dc0 │
│ 073fa4be4665f397a289842b1053229c │
│ 76de574e14e58baded25a12dce8075c1 │
│ 0db1181e0778609b581bf9a95b17f313 │
│ ccfc366f9a65ee1750a938bd18aa489f │
│ baed56f3eda9223b74c6cf175f05678e │
│ 500aced6001e75a49db10f0ae54f94f1 │
│ dbf76ef1323584fa387945f83b324534 │
│ 1f6a5335ecf1406eea5f2cccc0c5946f │
│ 142b0e3de54c110a3109b26c79d6ec2e │
│ 2deb17060fc1ce18a85eba953ddcdeaf │
│ 95442deb81a5d91c97c0df96b431634a │
│ ccfa13cff25aa5ad005e434ac68acaaa │
│ f494e4f6b6de7aeefe3af00acc8b3426 │
│ eae81d7a6951b80a04eb152e76e3ba55 │
│ 964937fd838e5fb7488cf417d7b60747 │
│ df926b7d1f6199f57548358c93ec9f39 │
│ dbfa3d8c05cc5d84083fc259a9feb5bc │
│ 615e54068238441742c4daf6a7b4ccff │
│ 7150a9da273995bcf6c7c5beeb3e5c42 │
│ e00ed9d20c3479f9f0e9727ca9d60946 │
│ 807303007d46225288462ecc115905fe │
└──────────────────────────────────┘

In [38]:
pl.read_database(
        query = """
        select *
        from raw.reviews
        where order_id = '565b0bdb5bfef65df5a23890967586f6';
        """, connection = engine
        )

shape: (2, 7)
┌──────────────────────────────────┬──────────────────────────────────┬──────────────┬──────────────────────┬────────────────────────┬──────────────────────┬─────────────────────────┐
│ review_id                        ┆ order_id                         ┆ review_score ┆ review_comment_title ┆ review_comment_message ┆ review_creation_date ┆ review_answer_timestamp │
│ ---                              ┆ ---                              ┆ ---          ┆ ---                  ┆ ---                    ┆ ---                  ┆ ---                     │
│ str                              ┆ str                              ┆ i64          ┆ null                 ┆ null                   ┆ str                  ┆ str                     │
╞══════════════════════════════════╪══════════════════════════════════╪══════════════╪══════════════════════╪════════════════════════╪══════════════════════╪═════════════════════════╡
│ b5170254268050e30337c3f408805395 ┆ 565b0bdb5bfef65df5a23890967586f6 ┆ 5            ┆ null                 ┆ null                   ┆ 2017-09-05 00:00:00  ┆ 2017-09-08 23:08:53     │
│ 9487a43f29708b00c4b6ef5af2441d1f ┆ 565b0bdb5bfef65df5a23890967586f6 ┆ 1            ┆ null                 ┆ null                   ┆ 2017-09-07 00:00:00  ┆ 2017-09-13 09:52:05     │
└──────────────────────────────────┴──────────────────────────────────┴──────────────┴──────────────────────┴────────────────────────┴──────────────────────┴─────────────────────────┘

In [39]:
pl.read_database(
        query = """
        select *
        from raw.products
        where product_weight_g is null;
        """, connection = engine
        )

shape: (2, 9)
┌──────────────────────────┬───────────────────────┬─────────────────────┬──────────────────────────┬────────────────────┬──────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ product_id               ┆ product_category_name ┆ product_name_lenght ┆ product_description_leng ┆ product_photos_qty ┆ product_weight_g ┆ product_length_cm ┆ product_height_cm ┆ product_width_cm │
│ ---                      ┆ ---                   ┆ ---                 ┆ ht                       ┆ ---                ┆ ---              ┆ ---               ┆ ---               ┆ ---              │
│ str                      ┆ str                   ┆ i64                 ┆ ---                      ┆ i64                ┆ null             ┆ null              ┆ null              ┆ null             │
│                          ┆                       ┆                     ┆ i64                      ┆                    ┆                  ┆                   ┆                   ┆                  │
╞══════════════════════════╪═══════════════════════╪═════════════════════╪══════════════════════════╪════════════════════╪══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 09ff539a621711667c43eba6 ┆ bebes                 ┆ 60                  ┆ 865                      ┆ 3                  ┆ null             ┆ null              ┆ null              ┆ null             │
│ a3bd8466                 ┆                       ┆                     ┆                          ┆                    ┆                  ┆                   ┆                   ┆                  │
│ 5eb564652db742ff8f28759c ┆ null                  ┆ null                ┆ null                     ┆ null               ┆ null             ┆ null              ┆ null              ┆ null             │
│ d8d2652a                 ┆                       ┆                     ┆                          ┆                    ┆                  ┆                   ┆                   ┆                  │
└──────────────────────────┴───────────────────────┴─────────────────────┴──────────────────────────┴────────────────────┴──────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [42]:
pl.read_database(
        query = """
        select count(*) as total_rows,
        count(distinct geolocation_zip_code_prefix) as unique_zips
        from raw.geolocation;
        """, connection = engine
        )

shape: (1, 2)
┌────────────┬─────────────┐
│ total_rows ┆ unique_zips │
│ ---        ┆ ---         │
│ i64        ┆ i64         │
╞════════════╪═════════════╡
│ 1000163    ┆ 19015       │
└────────────┴─────────────┘

In [45]:
pl.read_database(
        query = """
        select *
        from raw.geolocation
        where geolocation_zip_code_prefix = (
            select geolocation_zip_code_prefix
            from raw.geolocation
            group by 1
            having count(*) > 50
            limit 1)
        limit 20;
        """, connection = engine
        )

shape: (20, 5)
┌─────────────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┐
│ geolocation_zip_code_prefix ┆ geolocation_lat ┆ geolocation_lng ┆ geolocation_city ┆ geolocation_state │
│ ---                         ┆ ---             ┆ ---             ┆ ---              ┆ ---               │
│ i64                         ┆ f64             ┆ f64             ┆ str              ┆ str               │
╞═════════════════════════════╪═════════════════╪═════════════════╪══════════════════╪═══════════════════╡
│ 1014                        ┆ -23.546435      ┆ -46.63383       ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.547082      ┆ -46.633408      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546453      ┆ -46.633947      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546319      ┆ -46.633431      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546941      ┆ -46.633312      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546762      ┆ -46.633455      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.545338      ┆ -46.633582      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.547216      ┆ -46.633386      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.545949      ┆ -46.633501      ┆ são paulo        ┆ SP                │
│ 1014                        ┆ -23.547082      ┆ -46.633408      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546066      ┆ -46.633474      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.544632      ┆ -46.633937      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.545626      ┆ -46.633542      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.544632      ┆ -46.633937      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.545949      ┆ -46.633501      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546363      ┆ -46.633676      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.545338      ┆ -46.633582      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.545338      ┆ -46.633582      ┆ sao paulo        ┆ SP                │
│ 1014                        ┆ -23.546066      ┆ -46.633474      ┆ são paulo        ┆ SP                │
│ 1014                        ┆ -23.546363      ┆ -46.633676      ┆ sao paulo        ┆ SP                │
└─────────────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┘